### ISSUE TITLE
More detailed instructions on how to get started

### ISSUE THREAD

**Issue by krupis** [xanderhendriks/docker-stm32cubeide#5]
Hello. I am working with the STM32 project and would like to setup CI/CD pipeline to automatically build and generate .hex artifact upon each release. I have very minimal docker experience, I used esp-idf docker image before to do the same thing on a different MCU (ESP32) using the espressif/idf:v5.0.4 image. My .gitlab-ci.yml was as following:

```
stages:
  - build

esp_idf_generate_build_files:
  image: espressif/idf:v5.0.4
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  stage: build
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created
  before_script:
    - idf.py build
  script:
    - mkdir binaries;
    - mkdir full_binary;
    - cd build; 
    - echo ${CI_PROJECT_NAME}
    - esptool.py --chip esp32 merge_bin -o merged_fw.bin --flash_mode dio --flash_freq 40m --flash_size keep 0x1000 bootloader/bootloader.bin 0x10000 ${CI_PROJECT_NAME}.bin 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial.bin 0xf000 phy_init_data.bin
    - cd ..
    - cp build/${CI_PROJECT_NAME}.bin binaries/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.bin
    - cp build/merged_fw.bin binaries/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}_full.bin

    - cd binaries
    - zip ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}_binaries.zip *.bin # zip all .bin files
    - ls -la
    - cd ..
  after_script:
    - ls -l
    - cd full_binary
    - ls -l
    - touch JOB_ID.txt
    - echo GE_JOB_ID1=$CI_JOB_ID >> JOB_ID.txt
    - cat JOB_ID.txt
    - ls -l
  artifacts:
    paths:
      - binaries/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}_binaries.zip
    reports:
      # To ensure we've access to this file in the next stage
      dotenv: full_binary/JOB_ID.txt
 ```

The whole STM32 project is STM32CubeIDE based. After a quick search, I have found your docker image but with my limited docker knowledge I cannot fully figure out how to get this whole thing running as there seems to me that some steps are missing.

On my Ubuntu virtual machine, I have installed your docker image using the following command:

```
my_user@xxx-gitlab:~$ sudo docker pull xanderhendriks/stm32cubeide:7.0
7.0: Pulling from xanderhendriks/stm32cubeide
3b65ec22a9e9: Pull complete
10bf1cfff187: Pull complete
c13f6adea5ad: Pull complete
75133ffded2c: Pull complete
2832732aa9fd: Pull complete
Digest: sha256:3724d7ae4ea820ea75e6e2037bbd4d257b87190496f0289bbd86a0b6ecaaec21
Status: Downloaded newer image for xanderhendriks/stm32cubeide:7.0
docker.io/xanderhendriks/stm32cubeide:7.0
```

Additionally, I have cloned my STM32 project from the Gitlab to my Ubuntu virtual machine ( /tmp/test_project directory ):
```
my_user@xxx-gitlab:/tmp/test_project$ ls
my_stm32_project
```

I cannot fully figure out what are the next steps in order to build this project:
How to correctly run the docker image and what arguments do I need to pass? 
How to build the project? Do I need to have this project inside my Virtual machine or inside the docker container itself?
How to setup everything within the CI/CD script?

I would highly appreciate if you could clarify the above.. I think it would be helpful for others as well
